INSERT INTO student (student_name, student_surname, student_group_id, student_age) VALUES ( 'Anatoliy', 'Pushkarev', 1, 19),
                                                                                          ('Egor', 'Vidyakin', 1, 20), 
                                                                                          ('Mikhail', 'Muhorin', 1, 23),
                                                                                          ('Rostislav', 'Glizerin', 1, 23),
                                                                                          ('Daniil', 'Hudyakov', 1, 21),
                                                                                          ('Kamil', 'Kandaev', 2, 20),
                                                                                          ('Denis', 'Egoshin', 2, 19),
                                                                                          ('Katya', 'Potekhina', 2, 18),
                                                                                          ('Alexandra', 'Sayapina', 2, 19),
                                                                                          ('Ivan', 'Radushkin', 2, 21),
                                                                                          ('Kirill', 'Glushkov', 3, 24),
                                                                                          ('Darya', 'Uskova', 3, 22),
                                                                                          ('Artem', 'Arsibekov', 3, 21),
                                                                                          ('Lena', 'Kislicina', 3, 19),
                                                                                          ('Pavel', 'Danilov', 3, 19),
                                                                                          ('Nikolay', 'Moskvin', 4, 23),
                                                                                          ('Masha', 'Poptsova', 4, 22),
                                                                                          ('Ivan', 'Ivanov', 4, 22),
                                                                                          ('Alexandr', 'Petrov', 4, 24),
                                                                                          ('Michael', 'Jackson', 4, 25),
                                                                                          ('Arina', 'Ivanova', 5, 18),
                                                                                          ('Anna', 'Chernova', 5, 19),
                                                                                          ('Nastya', 'Dvornikova', 5, 20),
                                                                                          ('Alexandra', 'Kornilova', 5, 21),
                                                                                          ('Polina', 'Segova', 5, 19),
                                                                                          ('Xenia', 'Kiseleva', 6, 22),
                                                                                          ('Xenia', 'Alexeeva', 6, 21),
                                                                                          ('Pavel', 'Shipicin', 6, 20),
                                                                                          ('Roman', 'Cherbakov', 6, 20),
                                                                                          ('Maxim', 'Sergeev', 6, 21),
                                                                                          ('Alena', 'Tousheva', 7, 22),
                                                                                          ('Egor', 'Onosov', 7, 23),
                                                                                          ('Denis', 'Sapa', 7, 19),
                                                                                          ('Sonya', 'Zaharova', 7, 18),
                                                                                          ('Nastya', 'Ankudinova', 7, 20),
                                                                                          ('Alexandr', 'Pasternak', 8, 21),
                                                                                          ('Lena', 'Alexandrova', 8, 23),
                                                                                          ('Rinat', 'Gaysin', 8, 22),
                                                                                          ('Vlad', 'Istratov', 8, 20),
                                                                                          ('Miron', 'Gutsunaev', 8, 19),
                                                                                          ('Yaroslava', 'Rukavishnikova', 9, 23),
                                                                                          ('Nikolay', 'Chernov', 9, 23),
                                                                                          ('Lera', 'Oktanaeva', 9, 18),
                                                                                          ('Lena', 'Poyarkova', 9, 19),
                                                                                          ('Amelia', 'Tarasova', 9, 22);








